on:
  push:
    tags:
      - v*

name: Publish to VS Marketplace
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Publish extension
        run: |
          npm install -g vsce
          vsce publish --pat ${{ secrets.VSCE_TOKEN }}
